// <auto-generated>
//
//   Plugin.Binds.g.cs
//
//   GENERATED by scripts/gen_binds.py from schema/*.schema.json.
//   Do not hand-edit. Change the schema and re-run:
//
//       python3 scripts/gen_binds.py
//
//   One row per schema field with "in": "cfg" -- section, key, CLR type and
//   default. There is deliberately NO description argument. BepInEx writes a
//   "## <description>" block into ckf.hardmode.cfg for every bound key, so
//   binding without a description is what keeps the prose out of the file
//   (docs/gui-plan.md section 3.2). The "# Setting type:" and
//   "# Default value:" pair still appears: those two strings are literals
//   inside BepInEx.Core.dll with no public switch, and are out of scope.
//
//   The prose itself now lives in the schema's `doc` arrays, rendered into
//   docs/config-reference.md.
//
// </auto-generated>

using System;
using System.Collections.Generic;
using BepInEx.Configuration;

namespace CKFHardMode
{
    /// <summary>
    /// The single declaration of every key in ckf.hardmode.cfg.
    ///
    /// A subsystem binds through <see cref="Bind{T}"/> rather than calling
    /// <c>ConfigFile.Bind</c> itself, so the section, key, type and default
    /// are stated once, here, and match the schema by construction.
    ///
    /// Bind is still a real <c>ConfigFile.Bind</c> call made at the same point
    /// in startup as the hand-written call it replaced: BepInEx writes the file
    /// from the set of keys actually bound, and a key nothing binds is left in
    /// place as an orphan. Binding every key eagerly would change that, so this
    /// class does not do it.
    /// </summary>
    internal static class Binds
    {
        /// <summary>One declared cfg key. See <see cref="Def{T}"/> for the value.</summary>
        internal abstract class Def
        {
            internal readonly string Section;
            internal readonly string Key;

            protected Def(string section, string key)
            {
                Section = section;
                Key = key;
            }

            /// <summary>"Section.Key", the form used in the .cfg and the schema.</summary>
            internal string Id { get { return Section + "." + Key; } }

            /// <summary>The CLR type this key's default was declared with.</summary>
            internal abstract Type ValueType { get; }
        }

        /// <summary>A declared cfg key of a known type.</summary>
        internal sealed class Def<T> : Def
        {
            internal readonly T Default;

            internal Def(string section, string key, T defaultValue)
                : base(section, key)
            {
                Default = defaultValue;
            }

            internal override Type ValueType { get { return typeof(T); } }
        }

        /// <summary>Every key in ckf.hardmode.cfg, 1 of them.</summary>
        internal static readonly Def[] All =
        {
            new Def<bool>("General", "Enabled", true),
        };

        private static readonly Dictionary<string, Def> ById = BuildIndex();

        private static Dictionary<string, Def> BuildIndex()
        {
            var map = new Dictionary<string, Def>(All.Length, StringComparer.Ordinal);
            foreach (var def in All)
                map[def.Id] = def;
            return map;
        }

        /// <summary>
        /// Bind one declared key and return its entry.
        ///
        /// A key the table does not declare, or one asked for at the wrong type,
        /// is a defect in this file or in the caller -- not a configuration the
        /// player can reach. It logs and throws rather than handing back
        /// default(T), because a wrong-typed default that silently works is
        /// exactly the class of bug AGENTS.md section 3 is about: the caller
        /// would read a plausible number and have no way to tell it apart from
        /// a real one.
        /// </summary>
        internal static ConfigEntry<T> Bind<T>(ConfigFile config, string section, string key)
        {
            if (config == null) throw new ArgumentNullException("config");

            var id = section + "." + key;

            Def def;
            if (!ById.TryGetValue(id, out def))
                throw Fail("Binds: \"" + id + "\" is not declared in Plugin.Binds.g.cs. "
                         + "Add it to the matching schema/*.schema.json and re-run "
                         + "scripts/gen_binds.py.");

            var typed = def as Def<T>;
            if (typed == null)
                throw Fail("Binds: \"" + id + "\" is declared " + def.ValueType.Name
                         + " but was requested as " + typeof(T).Name + ".");

            // No description argument. See the header.
            return config.Bind(section, key, typed.Default);
        }

        /// <summary>Bind one declared key and return its value.</summary>
        internal static T Value<T>(ConfigFile config, string section, string key)
        {
            return Bind<T>(config, section, key).Value;
        }

        private static Exception Fail(string message)
        {
            // Plugin.Log is assigned first thing in Plugin.Load, but this can be
            // reached from a test harness where it is not.
            if (Plugin.Log != null) Plugin.Log.LogError(message);
            return new InvalidOperationException(message);
        }
    }
}
